server:
    port: 8550
    servlet:
        context-path: /kash

management:
    endpoints:
        web:
            base-path: /status
            path-mapping:
                health: healthcheck
---

spring:
    profiles: dev
server:
    port: 8551

---

spring:
    profiles: prod
server:
    port: 8552